### ISSUE TITLE
quarantine policy database generation

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/covid#10]
How states react with quarantine over time may be of interest as both a visualization, and for future research. We will collect and visualize state-wide data on quarantine policies in the US. This would be updated and validated on a weekly basis. 

Need to ID someone who is interested in starting this collection in a google spreadsheet. You can use the the appropriate state name/id from the states.geojson file in the data folder of this repo to make merging easier. Columns would indicate time/dates and we'll need to identify different categories/coding for different types of policies. Please use thread here for discussion of coding strategies for collaborative approval.

_Originally posted by @linqinyu in https://github.com/GeoDaCenter/covid/issues/6#issuecomment-599342259_

**Comment by linqinyu** [comment]
How about something like this: https://docs.google.com/spreadsheets/d/1qhI-8nEaSZnp_2rN7Wtg456P0EUreft9d6yyKhEANa8/edit?usp=sharing. Feel free to make edits! 

When I tried to set up a spreadsheet for this, it occurred to me that some policies are at a county level. For example, several California counties have issued ‘shelter in place’. So I added the county level. But I think there would be policies at the state level too. In those cases, I think we can just leave the county column blank. 

The final column: to include official sources for the policy, try to only include those from government websites to avoid potential misinterpretation.

**Comment by bibindvasu** [comment]
New York City has made announcements of deploying 1000 bed hosptial ship. Would such announcements be eligible to be added to the spreadsheet? @linqinyu the spreadsheet is in view mode currently. It can't be edited.

**Comment by linqinyu** [comment]
Thanks! 
I am not sure how these beds will be used? It may not belong to "quarantine" but I think it is good to include in the data collection for now. I also changed the spreadsheet to be editable. Let me know if it doesn't work!

**Comment by bibindvasu** [comment]
The spreadsheet is editable. I will start updating it. Thanks.

**Comment by linqinyu** [comment]
Great! Thanks!

**Comment by Makosak** [comment]
Updating this to a GOOD FIRST ISSUE for new volunteers. Please update the doc above with new policies.

**Comment by Makosak** [comment]
Closing in favor of other issues here -- other work is doing this already: https://www.nlc.org/program-initiative/covid-19-local-action-tracker
