### ISSUE TITLE
data: testing numbers, hospital beds by county

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/covid#12]
Who can help to crawl this website?

https://covid-19.direct/county/AZ/Maricopa

**Comment by lixun910** [comment]
get hospital information from:
https://www.arcgis.com/apps/opsdashboard/index.html#/8c4dcccd9e3845eb89f6401f919007f2

**Comment by Makosak** [comment]
Another data resource: A map of hospital capacities, including staffed all beds, ICU beds, and occupancies at the hospital level: https://www.covidcaremap.org/maps/us-healthcare-system-capacity/#3.85/38.63/-93.09.

**Comment by Makosak** [comment]
Closing this for now (hospital beds have been added). Will add separate issue: how we can start a new time-series dataset to track hospitalizations, etc?
