### ISSUE TITLE
space out dates in histogram x-axis more, so they're more legible

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/covid#15]

**Comment by jkoschinsky** [comment]
same with y-axis: only list every 2nd label?

**Comment by Makosak** [comment]
similar to user group feedback

**Comment by Makosak** [comment]
@ariisrael may be related to d3.helper post via Xun?

**Comment by ariisrael** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#15: Space out dates in histogram x-axis more for legibility](https://trello.com/c/CtsQfn2a/91-15-space-out-dates-in-histogram-x-axis-more-for-legibility)
