### ISSUE TITLE
add CSDS logo and "powered by GeoDa" with 2 URLs to map app

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/covid#16]
2 URLs:
https://geodacenter.github.io/
https://spatial.uchicago.edu/

2 logo options:
![CSDS_UniversityWordmark_Gray](https://user-images.githubusercontent.com/13679743/77681775-dd17ee80-6f63-11ea-8344-156ec1991bce.png)
![CSDS_UniversityWordmark_Maroon202](https://user-images.githubusercontent.com/13679743/77681784-e0ab7580-6f63-11ea-83a2-56f3f497c7fa.png)

**Comment by lixun910** [comment]
The map app will be embedded on the landing page, so the log will be added to the landing page.

**Comment by Makosak** [comment]
I just added to the atlas app too under the data source note -- got this one done! will push in a little bit.

**Comment by Makosak** [comment]
Added a new page **atlas.html** that has these updates. Xun you can view: https://github.com/GeoDaCenter/covid/blob/master/docs/atlas.html

This is a replica of the existing index.html but with a few minor edits to the legend, including logo here. Once we flip to the new landing page, could source the atlas.html file for the iframe instead.

**Comment by Makosak** [comment]
okay, it's now rendered for viewing -- closing comment.
file:///Users/maryniakolak/Documents/covid/docs/atlas.html
