### ISSUE TITLE
CSV-county merging

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/covid#2]
The CSV file we're getting likely just has state name and county name. We will need to merge this with the GIS shapefiles. Note that county names are not unique, but state + county names are unique. Need to identify someone to take this merging issue on as we'll like be merging on a daily basis.

**Comment by Makosak** [comment]
We need to ID someone who wants to lead this -- @linqinyu  has some initial information on merging so far.

Current plan: merge with combination state + county string

Current issues: @linqinyu can you list here?

**Comment by linqinyu** [comment]
Sure! The current issue is that two counties from different states can have the same name. For example, one King county from WA, another King county from TX. We need to create a unique ID based on both State name and County name.  Otherwise, the data will be incorrect.

**Comment by lixun910** [comment]
@linqinyu The python script has been updated to using the county_name+state_abbr as ID. Can you help to check if the results are correct?  see tools/counties_update.geojson

**Comment by lixun910** [comment]
@linqinyu Which file should I use to get the population data: data/county_pop.csv or data/county_pop_gender_age_2018.csv ?

**Comment by lanselin** [comment]
county_pop.csv is the five year average, that’s the one to use

**Comment by linqinyu** [comment]
Yes, that's right, thanks, Luc!

I also quickly checked the counties_update.geojson. It looks right to me! (I looked at counties with the same name but from different states and they do have different counts. So I think the merging is right!)
________________________________

**Comment by lixun910** [comment]
Great. Thanks, Qinyun! Thanks, Luc!

**Comment by Sihan-Mao** [comment]
The merge looks good to me too. Checked Washington and Jefferson Counties and they match the records on the website. Thanks @lixun910, @linqinyu and @lanselin!

**Comment by Makosak** [comment]
okay, closing! Thanks guys.
