### ISSUE TITLE
Volunteers: please add title, affiliation and URL

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/covid#22]
Hi everyone who volunteers on this project:

We are acknowledging all the volunteers here:
https://spatial.uchicago.edu/content/us-covid-19-atlas
with this page: https://spatial.uchicago.edu/content/volunteers-csds-covid-10-atlas

I'm missing title, affiliation and URL for these volunteers if you can please add to this ticket:
Sihan Mao
John Steill
Steve Goldstein
Sean Kent
Steven R Wangen
Yuetian Luo
Brian Yangell

Will then update the page.
Thx!

**Comment by linqinyu** [comment]
@JohnWSteill @SteveGoldstein @Sihan-Mao  cannot find others...will send out a message in slack as well.

**Comment by SteveGoldstein** [comment]
Steve Goldstein, Botany, Biostatistics and Medical Informatics. University of Wisconsin-Madison.

It's Brian Yandell

**Comment by linqinyu** [comment]
So sorry for the typo!!!

**Comment by JohnWSteill** [comment]
John Steill, Computational Biologist, Morgridge Institute of Research

**Comment by blue442** [comment]
Steven Wangen
Assistant Scientist at the Wisconsin Institute for Discovery
Data Scientist at the American Family Insurance Data Science Institute
University of Wisconsin - Madison

https://www.linkedin.com/in/steven-wangen/

Thanks!

**Comment by Makosak** [comment]
Volunteers -- is it okay if we find a photo/profile for you online? Or send us one. See growing page here: https://geodacenter.github.io/covid/about.html

**Comment by Sihan-Mao** [comment]
Sihan Mao, Senior Data & Policy Analyst, Department of Innovation & Performance, City of Pittsburgh
