### ISSUE TITLE
state characteristics?

### ISSUE THREAD

**Issue by lanselin** [GeoDaCenter/covid#224]
There seems to be a problem updating the characteristics pop up window when using
a state map after the county map.

Use case:
- check the county map, focus on a given county, say Cook, and bring up the county characteristics
- switch to state map, click on a state, say Illinois, characteristics remain for the last county and do 
   not update to the state, or clear

**Comment by nofurtherinformation** [comment]
A fix for this is currently lined up for the November release -- will follow up here when we merge and push live!

**Comment by nofurtherinformation** [comment]
This fix is now live with the November release! State data are now available in the data side panel.
