### ISSUE TITLE
d3.js helper

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/covid#23]
I don't realize there are so many volunteers here. Anyone who knows d3.js, you are welcome to improve the d3.js made charts: the line chart and the bar chart. E.g. add mouse over function to the line chart, or add  a navigation line to the line chart etc.

The code to create the line char is in index.js in functions:
addTrendLine() and updateTrendLine()

The code to create the bar chart is in index.js in function:
createTimeSlider()

**Comment by RandomFractals** [comment]
@lixun910 if you are planning to add more charts to this dashbord, I would suggest you integrate vega-lite instead for faster configuration and better charts display with more polished look and feel, UX, export options, etc.

see: https://github.com/vega/vega-lite

It is built on d3.js, just more dev and user friendly.

**Comment by nofurtherinformation** [comment]
The new release of the Atlas refactors into React, and we have implemented ReCharts as our library of choice (for now). New figures include a more interactive line chart and two-week historical trend lines in the data report panel on the right for cases, deaths, and testing. Thanks @RandomFractals for your suggestions here!

![image](https://user-images.githubusercontent.com/10041771/105383343-a2f49900-5bd6-11eb-9e15-6e184aab08c0.png)
![image](https://user-images.githubusercontent.com/10041771/105383412-b56ed280-5bd6-11eb-83cf-bb2cff8bef9a.png)
