### ISSUE TITLE
bubble chart option

### ISSUE THREAD

**Issue by palisades-lakes** [GeoDaCenter/covid#24]
Choropleths are great, but it does make it hard to see small counties, eg, Cook, Manhattan, San Francisco...
A bubble map,as in 
https://blog.mapbox.com/notable-maps-visualizing-covid-19-and-surrounding-impacts-951724cc4bd8
would be a good additional option.

**Comment by lixun910** [comment]
Thanks, @palisades-lakes ! we prefer cartogram (just added) since the bubbles on the map "cover" certain area, and oversized bubbles might mislead readers that all areas under the bubble are infected.

**Comment by palisades-lakes** [comment]
The cartogram is great, and bubbles certainly have the issues you
mentioned, but some tasks are easier with bubbles.
For example, if you want to pick out the hottest areas and understand where
they are. Hard to go from cartogram to geography, and with choropleths you
may miss some because they are too small.
A minor quibble: it might be nice if the cartogram cursor was a pointer,
rather than a hand --- it's a little difficult to tell which circle you are
pointing at.

Anyway, great work and thanks for sharing it.

**Comment by lixun910** [comment]
Yes, will change the cursor.  One thing I am adding: a search box, to zoom into the county/state you searched in regular map, may solve this issue?

**Comment by Makosak** [comment]
Good to close? Can add other feature updates as JS-volunteer issues.

**Comment by palisades-lakes** [comment]
ok
