### ISSUE TITLE
Add label (hover) to explain LISA legend

### ISSUE THREAD

**Issue by skent259** [GeoDaCenter/covid#25]
Suggesting a few potential enhancements to the map that I believe would increase the clarity of the message: 

- Outside users of this visualization may not understand "high-high", "high-low", "low-low" and "low-high" labels at first.  I found the meaning under methods, but maybe an image/legend can be included under "Covid clusters" to further explain what they mean
- [Opinion] the County, confirmed cases per 1M is a really high value add visual, and it might benefit from being the default value for the map.
- Round cases per 1M population in the legend (seems to be doing this already in the hover) to make it more readable

Happy to help if I can on this, just point me in the right direction!

**Comment by Makosak** [comment]
Will split this into a few issues later today or tomorrow... Thanks!!

**Comment by Makosak** [comment]
Updating this issue to focus on the first bullet point:

> Outside users of this visualization may not understand "high-high", "high-low", "low-low" and "low-high" labels at first. I found the meaning under methods, but maybe an image/legend can be included under "Covid clusters" to further explain what they mean.

From user group; perhaps as the legend is being hovered over (is that how you say it?) there would be a pop-up explaining what each category would be.

**Comment by Makosak** [comment]
@ariisrael @rbrtmrtn We can create some content to add for this, but this would be a feature over the "legend" colors.
