### ISSUE TITLE
Generate summary report twice every week

### ISSUE THREAD

**Issue by linqinyu** [GeoDaCenter/covid#26]
Generate a report for regional clusters. For each regional cluster, the current plan is to include the following information: a list of counties, # of counties, total population, total confirmed cases, total death counts, the fatality rate, confirmed cases per 1M, death counts per 1M, and a figure for this particular cluster. 
The current plan is to update this report every 3 days, twice a week. May change later. The movie/gif will also be updated with this report. 
Suggestions and comments are always welcome!

**Comment by lixun910** [comment]
Anyone knows how to create gif (small size and high quality)? Thanks!

**Comment by blue442** [comment]
Imagemagick (https://imagemagick.org/index.php) is the old standby for
that, and works great, although it's an external program. It is run via the
command line though so can be automated using subprocess in python if
that's helpful. Let me know if you want help getting something set up.

-Steve

**Comment by jkoschinsky** [comment]
how about adding a comparison to the previous reports, i.e. indicators of growth/stability/reduction?



<https://spatial-data-science-conference.com/>
________________________________

**Comment by lixun910** [comment]
Some states are providing more data: see 

https://coronavirus.iowa.gov/

Current hospitalized 
Never hospitalized 
Discharged & recovering
Deceased


Xun Li, Ph.D.

Assistant Director of Data Science
Center for Spatial Data Science
University of Chicago

**Comment by linqinyu** [comment]
@lixun910 What about adding this to the spreadsheet Marynia created: https://docs.google.com/spreadsheets/d/1b3ElJC8AnwnYfBupBmoJEZJ8D53YfF719R2AL4ierb0/edit#gid=0. 
There is already one row for IA here. So I just added another link. The cases(-) and hospitalized are only at the state level, right?

**Comment by linqinyu** [comment]
@blue442 Thank you very much for the information! Very helpful. I will try myself first and let you know if I need any help!

**Comment by linqinyu** [comment]
@jkoschinsky Good idea! I will try to show the change in each regional cluster. Thx!

**Comment by Makosak** [comment]
Closing this for now -- id'd as not essential priority that can be error-prone. May re-open in the future.
