### ISSUE TITLE
Website: Drop down menu of data source didn't show correctly

### ISSUE THREAD

**Issue by jinfei1125** [GeoDaCenter/covid#265]
On the website, for some data types such as Mobility, the only available data source is SafeGraph, but it still shows CDC.
![image](https://user-images.githubusercontent.com/72103935/126848581-cbd0a53b-b79e-4594-be70-8ff164447076.png)

**Comment by nofurtherinformation** [comment]
Thank you for tagging this!

This issue was caused by tabular data being attributed to different geojson boundaries, and has been updated to correctly identify the dataset provider in the select menu when the base geojson and tabular data providers are not the same.
