### ISSUE TITLE
add press tab to website

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/covid#27]
https://www.vox.com/2020/3/28/21197421/usa-coronavirus-covid-19-rural-america
https://news.uchicago.edu/story/state-level-data-misses-growing-coronavirus-hot-spots-us-including-south

also: NPR and maybe Wall Street Journal, Scientific American

<img width="1638" alt="uchicago news home page" src="https://user-images.githubusercontent.com/13679743/77852840-5f8ff080-71a6-11ea-912c-a312302ab34a.png">

**Comment by linqinyu** [comment]
From Julia's previous emails: 
https://www.businessinsider.com/next-wave-of-coronavirus-national-epidemic-new-orleans-philadelphia-2020-3.

**Comment by Makosak** [comment]
Scientific American:
https://www.scientificamerican.com/article/map-reveals-hidden-u-s-hotspots-of-coronavirus-infection/?fbclid=IwAR08weiTCQTmzeSd7harTwPDR7dgQEbUZYCr0CdJhEYJp4OK7ps9fgu7hgA

WGN:
https://wgntv.com/news/medical-watch/small-areas-hit-hard-by-covid-19-find-representation-in-u-of-c-map/

**Comment by Makosak** [comment]
Another one (different from first business insider):
 https://www.businessinsider.com/coronavirus-hotspot-in-the-us-south-states-covid-19-pandemic-2020-4

**Comment by jkoschinsky** [comment]
https://abcnews.go.com/Health/surprising-covid-19-hot-spots-coronavirus-threatens-rural/story?id=69940146

**Comment by jkoschinsky** [comment]
https://www.youtube.com/watch?v=uqGXzWCD9Xk

**Comment by jkoschinsky** [comment]
https://www.washingtonpost.com/politics/even-as-deaths-mount-officials-see-signs-pandemics-toll-may-not-match-worst-fears/2020/04/07/cb2d2290-78d1-11ea-9bee-c5bf9d2e3288_story.html

"Marynia Kolak, assistant director of health informatics at the University of Chicago’s Center for Spatial Data Science, …”

**Comment by jkoschinsky** [comment]
**Media Coverage of CSDS U.S. COVID-19 Atlas**

Washington Post: Even as deaths mount, officials see signs pandemic’s toll may not match worst fears (April 8)
https://www.washingtonpost.com/politics/even-as-deaths-mount-officials-see-signs-pandemics-toll-may-not-match-worst-fears/2020/04/07/cb2d2290-78d1-11ea-9bee-c5bf9d2e3288_story.html

CBS This Morning: How the coronavirus is impacting rural areas (April 6)
https://www.youtube.com/watch?v=uqGXzWCD9Xk

ABC News: Surprising COVID-19 hot spots: Why coronavirus still threatens rural areas (April 4)
https://abcnews.go.com/Health/surprising-covid-19-hot-spots-coronavirus-threatens-rural/story?id=69940146

Daily Mail: America's hidden hotspots: Shocking maps reveal how rural areas and small communities are some of the hardest hit by coronavirus as hospitals are overwhelmed just like in New York and New Orleans (April 4)
https://www.dailymail.co.uk/news/article-8186581/Americas-hidden-hotspots-selfish-coronavirus-refugees-spread-disease.html

The Root: 8 of the 10 Worst Coronavirus Hot Spots Are in the South. Apparently, Republican Governors Just Found Out About the Pandemic (April 3)
https://www.theroot.com/8-of-the-10-worst-coronavirus-hot-spots-are-in-the-sout-1842648491

Scientific American: Map Reveals Hidden U.S. Hotspots of Coronavirus Infection (April 2)
https://www.scientificamerican.com/article/map-reveals-hidden-u-s-hotspots-of-coronavirus-infection/?fbclid=IwAR08weiTCQTmzeSd7harTwPDR7dgQEbUZYCr0CdJhEYJp4OK7ps9fgu7hgA

Business Insider: New data reveals coronavirus hotspots brewing across the south, where the pandemic is set to 'hit hard'(April 2)
https://www.businessinsider.com/coronavirus-hotspot-in-the-us-south-states-covid-19-pandemic-2020-4

WGN: Small areas hit hard by COVID-19 find representation in U of C map (March 31)
https://wgntv.com/news/medical-watch/small-areas-hit-hard-by-covid-19-find-representation-in-u-of-c-map/

Business Insider: The next wave of coronavirus outbreaks is threatening cities from New Orleans to Philadelphia, and it reveals the US is on pace for a national epidemic (March 30)
https://www.businessinsider.com/next-wave-of-coronavirus-national-epidemic-new-orleans-philadelphia-2020-3

International Business Times: Coronavirus USA: Second Wave Of Outbreak In Fall Possible, Fauci Warns (March 30)
https://www.ibtimes.com/coronavirus-usa-second-wave-outbreak-fall-possible-fauci-warns-2949741

Vox: The Coronavirus May Hit Rural America Later - and Harder (March 28)
https://www.vox.com/2020/3/28/21197421/usa-coronavirus-covid-19-rural-america

UChicago News: State-level data misses growing coronavirus hot spots in the U.S., including in the South (March 26)
https://news.uchicago.edu/story/state-level-data-misses-growing-coronavirus-hot-spots-us-including-south

**Comment by jkoschinsky** [comment]
https://www.nytimes.com/2020/04/10/nyregion/coronavirus-new-yorkers-leave.html

**Comment by Makosak** [comment]
Should be updated by end of day!
