### ISSUE TITLE
Add baseline-forecast model for counties

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/covid#31]
Tagging Xun and Pedro; Pedro's code is almost ready to go, and needs to be integrated. Would update daily based on new data.

Later we'll need to identify an easy way for groups to add their models in the format we need, etc.

**Comment by Makosak** [comment]
This can be multiple tasks -- merging and data protocol; visualization itself; etc. Let us know how we can help!

**Comment by pedrovma** [comment]
The latest R code I sent is already ready to go, unless we find any bug in it. It spits a table with the predicted total cases by counties/states for each of the 15 days ahead of the latest data on this git. I believe now it is just a matter of plugging that into the Atlas template to show the absolute values/spatial clusters, but I absolutely lack technical capacity to do this. Up for grabs?

**Comment by ariisrael** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#31: Add baseline-forecast model for counties](https://trello.com/c/WTqHsggH/101-31-add-baseline-forecast-model-for-counties)
