### ISSUE TITLE
Join DesCartes Lab Mobility Index data for visualization

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/covid#33]
Add mobility index dataset for counties (proxy for social distancing, something > nothing), using DesCartes Lab's Mobility index data. Be sure to call this "Mobility Index" and source DesCarte lab (link back to their Github).

https://github.com/descarteslabs/DL-COVID-19

UI consideration: Visualize this as choropleth and clustering as default? Or is there a better way?
Also we will likely get at least 1 more social-distancing-proxy county-level dataset, so thinking about how that is presented?

Note: this could be split into 2 tasks (data merge, JS viz), depends on who claims it!

**Comment by Makosak** [comment]
This will be another time-series dataset to add, like USAfacts or 1P3A. Data is cleaned and ready to join via FIPS at county or state (all in one file) -- https://github.com/descarteslabs/DL-COVID-19/blob/master/DL-us-m50.csv and we would visualize the index shown. @linqinyu what would be best way to add and update daily, like the other data?

**Comment by linqinyu** [comment]
Then this can be wrapped together with USAFacts & NYTimes (from the Berkely group). We can automate the update for these three datasets I think: extract them every day at a certain time. I need to merge this dataset with our geojson file to make sure the county names are right.
________________________________

**Comment by ariisrael** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#33: Join DesCartes Lab Mobility data for visualization](https://trello.com/c/fyw2O9rn/100-33-join-descartes-lab-mobility-data-for-visualization)
