### ISSUE TITLE
Time Label

### ISSUE THREAD

**Issue by ryanwyg** [GeoDaCenter/covid#34]
The "Show Time Label" option returns very big labels where only the year "2020" is available. I do not know if this is intentional as the data from 1p3a API might still be lagged or if this is a bug? This has been a consistent issue with the browsers I have (Mac, Safari and Opera, and Windows, Opera.)

**Comment by ryanwyg** [comment]
Also another UI suggestion: Adding a logarithmic scale option for cases would be helpful in identifying growth trends.

**Comment by Makosak** [comment]
great points, thanks! if you can add the log scale as another issue -- second request we had for that so good to flag.

**Comment by ariisrael** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#34: Time Label](https://trello.com/c/j3bRagGL/99-34-time-label)
