### ISSUE TITLE
Log scale for cases stats graph

### ISSUE THREAD

**Issue by ryanwyg** [GeoDaCenter/covid#36]
UI suggestion: Adding a logarithmic scale option for cases would be helpful in identifying growth trends.

**Comment by nofurtherinformation** [comment]
This feature is now live on the new release of the Atlas! You can now click the linear scale/log scale switch on the line chart panel to swap between Y-axis scales.

![image](https://user-images.githubusercontent.com/10041771/105382877-28c41480-5bd6-11eb-97e5-2bc2fde5dc73.png)
