### ISSUE TITLE
User Session for Map w/ Reset as Optional, not Default

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/covid#37]
Generate a user session for the map, so that the map doesn't re-initialize and reset every time a new selection is made. For example, if a user zooms into a region, using the temporal slider or clicking a different variable forces them out to the whole US again.  Then we could use a button to reset as an option, vs making it a default for any task. I think this may be the "buggy" experience some have been noting.

Have some sample code for that here: https://github.com/Makosak/chihealthaccess/blob/master/js/maps_lib.js but would need to be re-tooled, and I'm a bit rusty.

**Comment by Makosak** [comment]
Adding as a task for refactoring this week @rbrtmrtn

**Comment by rbrtmrtn** [comment]
@Makosak I can definitely roll this in to the refactor!

**Comment by ariisrael** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#37: User Session for Map w/ Reset as optional, not default](https://trello.com/c/98rXrr9v/98-37-user-session-for-map-w-reset-as-optional-not-default)
