### ISSUE TITLE
Join Limited Engagement Index from Booth Team

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/covid#38]
another social distancing proxy

**Comment by Makosak** [comment]
The data are now available at https://github.com/COVIDExposureIndices/COVIDExposureIndices.

**Comment by Makosak** [comment]
Oof, this will be a heavy lift. This actually returns a 2k x 2k origin:destination matrix for all counties (or almost all, as we're missing 1k). It's updated daily. This could be super useful but we'll need to build a pipeline to incorporate. @linqinyu what do you think of this as a priority or not? @rbrtmrtn may be interested in a long-term solution if we incorporate?

From the site:
**County-level location exposure index (LEX):** Among smartphones that pinged in a given county today, what share of those devices pinged in each county at least once during the previous 14 days? The daily county-level LEX is an approximately 2000-by-2000 matrix in which each cell reports, among devices that pinged today in the column county, the share of devices that pinged in the row county at least once during the previous 14 days.

**Comment by rbrtmrtn** [comment]
This sounds like a really neat dataset! Agreed that the matrix might be a little tricky to bring in as is. One question for you @Makosak @linqinyu that might point us toward a better data structure... did you have initial thoughts on how to visualize this? I was thinking it might be cool to draw lines between the origin county and top n destinations on hover. Or might be simpler to just aggregate movement to the county level. Curious to get your thoughts!

**Comment by lixun910** [comment]
This data bring me this map: https://deck.gl/showcases/gallery/arc-layer
😊

**Comment by rbrtmrtn** [comment]
That's awesome @lixun910! 😄

**Comment by linqinyu** [comment]
The visualization is great!!

But I don't see this as a high priority? Definitely on the list for the long-term. And I think it would be great to look at the change over time for these data.
________________________________

**Comment by Makosak** [comment]
Okay, we can put this in a future enhancement setting then, after we get a simpler mobility measure included. Love the idea of using flows to proxy this (between the origin county and top n destinations on hover), though!

**Comment by Makosak** [comment]
Closing for now but we can reopen when ready.
