### ISSUE TITLE
Redesign landing page

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/covid#40]

**Comment by linqinyu** [comment]
Need to add coauthors. & Update the data source information (not only 1P3A but also other data sources).

**Comment by Makosak** [comment]
@linqinyu coauthors and data page are up!

For redesign page -- seeking inspiration from favorite web maps via @ariisrael's request. Can add to our slack channel #6 or for those outside core group, can add here.

**Comment by ariisrael** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#40: Redesign landing page](https://trello.com/c/twijikom/88-40-redesign-landing-page)

**Comment by Makosak** [comment]
In progress -- to be updated by July 6th.
