### ISSUE TITLE
Add New York Times data & Predicted death at the county level

### ISSUE THREAD

**Issue by linqinyu** [GeoDaCenter/covid#41]
The data are shared by the Berkely group: 
NewYorkTimes data will be updated here: 
https://github.com/Yu-Group/covid19-severity-prediction/blob/master/data/nytimes.

**Comment by rbrtmrtn** [comment]
Hi @linqinyu, I noticed the above link must have changed at some point. Is this the data we'd like to load in? It's the closest thing I could find 🧐 

https://github.com/Yu-Group/covid19-severity-prediction/blob/master/data/county_level/processed/nytimes_infections/nytimes_infections.csv
