### ISSUE TITLE
Automated data flows

### ISSUE THREAD

**Issue by rbrtmrtn** [GeoDaCenter/covid#43]
Hello everyone!

I've been diving into the code this week to get a better feel for how data flows from 1P3A and USAFacts all the way to the front end. This is really fantastic work and I think will make a great foundation as we keep iterating on the back end!

I was hoping to kick off a conversation around how we might be able to translate the [`hourly_update.py`](https://github.com/GeoDaCenter/covid/blob/master/tools/hourly_update.py) script into something that could take on the character of an automated data pipeline. I had a few ideas I wanted to share, and looking forward to getting your input as well @jkoschinsky @Makosak @lixun910 @linqinyu 

Broadly speaking, I think it would be helpful to have two types of Python scripts we use to pipe data into the app: "fetchers" and "transforms".

A fetcher would be a simple script that runs on a schedule and dumps data as-is from one of our sources into file storage (we can think of this an an archive). For instance, there could be a fetcher for 1P3A cases that runs on the hour and drops a file called `1P3A_cases_<timestamp>.csv` into an Amazon S3 bucket. That bucket would be solely for keeping snapshots of the source data in the original.

When the fetcher is done, it would kick off a transform script that takes the source data, does whatever's needed to get it ready for the Atlas (e.g. aggregates cases by county/state), and puts the result into a separate S3 bucket that's just for derived data products.

In some ways this is quite similar to what's already happening (I see `hourly_update.py` has distinct steps for fetching and transforming, so I don't think that code would have to change much at all!) But I did want point out a few potential benefits to packaging this process for the cloud, as well as externalizing data from the Git repo:

- The S3 bucket that archives our source data could essentially become a warehouse of COVID data by the hour. My assumption is this will be very powerful not just for real-time analysis, but also if any new research interests come up down the line. (It sounds like this may have been a goal of the project from the start, but let me know if I got that wrong or this feels out of scope!)
- Storing data in S3 will allow us to capture data at a high temporal resolution and add new sources without having to worry about the size of the Git repo. Also, having the snapshots side-by-side in a file store (vs. tracked in the Git history) should make it easier to iterate over them during any sort of time-series analysis.
- Not a super high priority, but it's also nice to be able to "set it and forget it" by automating the flow of data 😄 

A few quick notes on error handling:

- It shouldn't be hard to set up alerts so if anything goes wrong we would get an email, Slack message, etc.
- The `unmatched.txt` file that logs counties without matches would stay the same—it would just live in S3, but we could still review it manually and add exceptions to the code where they're needed.

As far as implementing this, it shouldn't be hard to adapt `hourly_update.py` into two AWS Lambda functions (one fetcher, one transform). We can schedule the fetcher to run on the hour with [CloudWatch Events](https://docs.aws.amazon.com/lambda/latest/dg/services-cloudwatchevents.html). On the front end, the app would just pull the CSV/JSON files it needs from S3 rather than GitHub.

I think that about sums it up—I hope I explained this well enough but please let me know if I can expand on anything! And of course, I don't want to overcomplicate a process that's been working very well, but it sounds like the Atlas may be reaching a scale of data where going to the cloud could have some tangible benefits.

Looking forward to hearing everyone's thoughts on next steps for the back end and continuing the conversation!

**Comment by lixun910** [comment]
Thanks, Robert! It looks good for a long term solution. How much time do you think it will need to get it done? Maybe Qinyun can show you more on our daily update routine, so you can prioritize the tasks.

 One priority is to save the 1p3a results into two csv files like USAFacts (not geojson), so the data parsing in index.js can be simplified, and also the data size is significantly reduced  (geojson file of 1p3a is about 10M, so we have extra zip and unzip procedure in index.js to make it fast, which is not efficient — compare to USAFacts 300k csv file and 2M geojson).

Thanks!

Xun 


Xun Li, Ph.D.

Assistant Director of Data Science
Center for Spatial Data Science
University of Chicago

**Comment by linqinyu** [comment]
The procedure looks good to me!

A note is that we will switch to our UC Berkeley group to extract USAFacts and NYT data (hopefully next week). I guess this can help make automation easier since they will check the data before us. We only need to manually check 1P3A.

@Robert Martin<mailto:rmartin@rmart.in> I will send you the daily updates procedure we are doing right now. You can take a look at it when you get time!

________________________________

**Comment by rbrtmrtn** [comment]
Thank you for the feedback @lixun910 and @linqinyu, this is very helpful!

I was thinking maybe we could start by going over the data sources on our call tomorrow—it would be great to hear a bit more from you about what the Berkeley group is doing, just so we aren't duplicating efforts/"sources of truth". 

Thank you and looking forward to chatting!

**Comment by ariisrael** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#43: Automated data flows](https://trello.com/c/DnCXt74b/97-43-automated-data-flows)

**Comment by Makosak** [comment]
IP, completion date : June 26th projection
