### ISSUE TITLE
LISA map: ring of coldspots around border

### ISSUE THREAD

**Issue by jkoschinsky** [GeoDaCenter/covid#44]
(based on conversation with Jamie):

FYI: On March 5, there's a ring of coldspots around the US border. This is probably an artifact of the weights?

<img width="1305" alt="Screen Shot 2020-04-18 at 9 57 09 AM" src="https://user-images.githubusercontent.com/13679743/79641105-fecb5680-815a-11ea-99ee-0533875b6c29.png">

**Comment by Makosak** [comment]
Yes I agree, lots of weird things happen with the coldspots overall, it's a tricky and imperfect thing.

**Comment by Makosak** [comment]
Closing for now, can reopen if we update LISA in refactor
