### ISSUE TITLE
Add Berkeley forecasting data

### ISSUE THREAD

**Issue by rbrtmrtn** [GeoDaCenter/covid#47]
Data is available here: https://docs.google.com/spreadsheets/d/1ZSG7o4cV-G0Zg3wlgJpB2Zvg-vEN1i_76n2I-djL0Dk/edit#gid=1341003284

**Comment by rbrtmrtn** [comment]
@Makosak @linqinyu just cross-posting here what we had discussed in Slack, with a little more detail - no need to follow up unless you have additional thoughts :)

For bringing the forecast data into the Atlas, we had discussed possibly accessing it directly in the browser via the Google Sheets API, but it looks like there's some authentication that needs to happen to do that:
https://developers.google.com/sheets/api/quickstart/js

Since we don't own the document, I'm not immediately sure how that would work.

For now I can commit a single snapshot of this data to the repo for demo purposes, and we can figure out a longer-term solution after the demo if that's OK with the team.

**Comment by linqinyu** [comment]
We can bring this up in Thursday's meeting. 

Also waiting to hear from them regarding data for two counties in AK.
