### ISSUE TITLE
For Discussion: Unassigned county cases

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/covid#5]
Several cases in the county-level dataset we'll be getting will be listed as "unassigned." These are usually updated within a day or two to the right county, but it seems that some states are better about this than others. Something to think about and discuss. What will our protocol be?

**Comment by linqinyu** [comment]
How about every time we update we check any changes on previous "unassigned" cases? Any more efficient ways to do this?

**Comment by Makosak** [comment]
Right now, goal will be to keep unassigned in separate category for each state. This would get reviewed weekly --> moving to validation check in separate issue.
