### ISSUE TITLE
Update data/variable dropdowns to select elements

### ISSUE THREAD

**Issue by ariisrael** [GeoDaCenter/covid#52]
Right now the data and variable dropdown elements are divs not select elements. Confuses some users who don't realize they are dropdowns.

**Comment by ariisrael** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#52: Update data/variable dropdowns to select elements](https://trello.com/c/eZEfDZ1A/94-52-update-data-variable-dropdowns-to-select-elements)

**Comment by Makosak** [comment]
postponed
