### ISSUE TITLE
Add New York Times data to map

### ISSUE THREAD

**Issue by ariisrael** [GeoDaCenter/covid#55]

**Comment by ariisrael** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#55: Add New York Times data to map](https://trello.com/c/S9ARb9Sc/93-55-add-new-york-times-data-to-map)

**Comment by nofurtherinformation** [comment]
New York Times state and county data has been added the Atlas in the new release. You can now selected New York Times in the variables panel on the left hand side of the page for relevant variables!

![image](https://user-images.githubusercontent.com/10041771/105383131-6628a200-5bd6-11eb-9b9e-8045de62f352.png)
