### ISSUE TITLE
Highlight boundaries of selected county/state

### ISSUE THREAD

**Issue by ariisrael** [GeoDaCenter/covid#59]
Possibly to replace the tooltip, but boundaries on hover and select should be different colors or thicknesses to make it clear which region is selected.

**Comment by ariisrael** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#59: Highlight boundaries of selected county/state](https://trello.com/c/VAgBiILE/85-59-highlight-boundaries-of-selected-county-state)

**Comment by Makosak** [comment]
Postponed
