### ISSUE TITLE
Empirical Networks

### ISSUE THREAD

**Issue by JamesSaxon** [GeoDaCenter/covid#6]
Two successive rough questions:

1. Can we show that empirical mobility patterns are better predictors of transmission than simple spatial proximity?
2. Can we measure the response on the empirical network, to understand how that affects transmission -- 
  a. How has the network structure changed (presumably, a LOT).
  b. Do current (post-quarantine) networks predict loads better than status-quo networks?
  c. Is the observed quarantining linked to reduced transmission in simple models?
  d. If certain communities have quarantined more-effectively than others, does this affect their case load?

**Comment by linqinyu** [comment]
I have been thinking about this to study what has happened in China two weeks ago! I would be very excited if we can look into some causal analysis regarding how the virus got spread and how different types of interventions (e.g., different tastes of lockdown) reduce the spread. 
A few very rough thoughts: 
1. Cancellation of flights will change the way of spreading. We can track the policies regarding travel ban at the national level. We may also collect data for when each university decided to start virtual learning & when each company decided to start work from home. 
2. Local-level: how different are the quarantine policies are? How do these policies change over time? 
3. May apply agent-based modeling.   
I think spreading is definitely a result of a combination of social network and spatial proximity. The tricky problem here is that it is too difficult to collect social network data at the individual level, especially when we arrive at community transmission.

**Comment by Makosak** [comment]
Closing as Jamie is working on this separately, and Qinyun as well.
