### ISSUE TITLE
Add state testing %

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/covid#62]
Add state testing % to show up in the county dashboard. This will help give healthworkers/planners some point of reference on how accurate the confirmed cases will be. Requested via stakeholder/partners.

Need to identify a data source for state-wide metrics that could be updated regularly - would JHU have this now? We know county-level data is not possible at this stage.

**Comment by ariisrael** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#62: Add state testing %](https://trello.com/c/ChcNOLGz/84-62-add-state-testing)

**Comment by Makosak** [comment]
integrated in update plan
