### ISSUE TITLE
population data

### ISSUE THREAD

**Issue by lixun910** [GeoDaCenter/covid#7]
Does anyone have the latest population data for states and counties?

**Comment by linqinyu** [comment]
I just upload the county population: county_pop.csv (based on ACS 2018), in the data folder. Five variables are included for each county: total population, male, female, male above age 50, female above age 50. I thought we might create some indicator for something like population at risk? Based on 1point3acres (probably other references can be found as well), the median age is 49 that is why I chose 50 as a threshold. Also, more than 70% of the patients are male, so I separated gender groups.

**Comment by lanselin** [comment]
There is some evidence from Europe that young people are affected as well and are just as much
at risk as older ones, so that would argue against a cut-off at 50.

**Comment by linqinyu** [comment]
Got it! Then we can just use the total population.
________________________________

**Comment by Sihan-Mao** [comment]
Added another county level population estimates (2018) with gender and age groups from Census Bureau. https://factfinder.census.gov/faces/tableservices/jsf/pages/productview.xhtml?pid=PEP_2018_PEPAGESEX&prodType=table

**Comment by linqinyu** [comment]
Thanks! I used the 2014-2018 5-year ACS (more reliable but less current). I think you used the 2018 1-year estimate (more current but less reliable). I guess the results should not be too different? But if we want to emphasize "most current", I agree that we should go with the 2018 1-year estimate.
________________________________

**Comment by lanselin** [comment]
I would suggest to go with the five year average since the one year samples are notoriously poor at small spatial scales, even though they are more recent.

**Comment by Makosak** [comment]
Agreed, let's stick to 5-year estimates for better reliabiity.

**Comment by linqinyu** [comment]
Sounds good. The 5-year estimate (2014-2018) population data is available as "county_pop.csv" in the data folder. We can use the total population for now (the column named as "total_population".)

**Comment by Makosak** [comment]
Perfect -- @lixun910 let us know if you need anything else, otherwise closing this.
