### ISSUE TITLE
Testing locations

### ISSUE THREAD

**Issue by Makosak** [GeoDaCenter/covid#8]
We need someone to start reviewing the spreadsheet linked here and create a pilot testing location dataset that Xun could add as a layer to the map. We need to:

- copy this info over to new spreadsheet. We could use the "IMPORTRANGE" function in Google Spreadsheets to update automatically.
- generate new column -- address that is in formatting for the RCC Geocoder at Uchicago
- geocode the data using RCC geocoder
- think about process for updating this daily
- add updated file to data folder to close issue

Qinyun's reference:

> Link for the spreadsheet that includes all testing places (the point (1) I mentioned): https://docs.google.com/spreadsheets/d/1svnaZ2UG_ryFr8jjqVx7ZVZksBue4EQUJ4dolMDJx70/edit#gid=0.
> 
> _Originally posted by @linqinyu in https://github.com/GeoDaCenter/covid/issues/3#issuecomment-601294268_

**Comment by Makosak** [comment]
okay to split this into 2 issues if multiple people interested --- one person can focus on geocoding testing locations in the current version, another person can focus on updating/workflow protocol.

**Comment by linqinyu** [comment]
This is their working excel: https://docs.google.com/spreadsheets/d/1cnvNjWRxqE_WHSekbM9mC9OtSSx5Jws4Ngot3N-NE5s/edit#gid=0. I have added a comment asking whether it is OK/desirable to add two columns for latitude and longitude.

**Comment by Makosak** [comment]
Closing for now as we will instead switch to need for hospitalization + testing results data.
